"use client";

import { FormEvent, useRef, useState } from "react";
import { createClient } from "@/lib/supabase";

export default function NewAssessmentPage() {
  const [make,setMake]=useState(""); const [model,setModel]=useState(""); const [year,setYear]=useState(""); const [registration,setRegistration]=useState(""); const [city,setCity]=useState(""); const [photos,setPhotos]=useState<File[]>([]); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false); const input=useRef<HTMLInputElement>(null); const supabase=createClient();
  function addPhotos(list: FileList|null){ if(!list)return; const next=[...photos,...Array.from(list)].filter((f,i,a)=>i===a.findIndex(x=>x.name===f.name&&x.size===f.size)); setPhotos(next.slice(0,10)); }
  async function submit(e:FormEvent){ e.preventDefault(); if(!photos.length){setMessage("Please add at least one damage photo.");return;} setBusy(true); setMessage("Saving assessment..."); const {data:{user}}=await supabase.auth.getUser(); if(!user){window.location.href="/login";return;} const {data:vehicle,error:ve}=await supabase.from("vehicles").insert({user_id:user.id,make,model,year:Number(year),registration_number:registration||null}).select("id").single(); if(ve){setBusy(false);setMessage(ve.message);return;} const {data:assessment,error:ae}=await supabase.from("assessments").insert({user_id:user.id,vehicle_id:vehicle.id,city,status:"pending"}).select("id").single(); if(ae){setBusy(false);setMessage(ae.message);return;} for(const file of photos){const path=`${user.id}/${assessment.id}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`; const {error:up}=await supabase.storage.from("carfix-damage-photos").upload(path,file,{contentType:file.type||"image/jpeg",upsert:false}); if(up){setBusy(false);setMessage(`Photo upload failed: ${up.message}`);return;} const {error:pe}=await supabase.from("assessment_photos").insert({assessment_id:assessment.id,storage_path:path,photo_type:"damage"}); if(pe){setBusy(false);setMessage(pe.message);return;}} window.location.href=`/assessments/${assessment.id}`; }
  return <main className="section"><div className="container" style={{maxWidth:760}}><a href="/dashboard">← Dashboard</a><div className="card" style={{marginTop:25}}><p className="muted">Step 1</p><h1>Start a car damage assessment</h1><p className="muted">Add the vehicle details, city, and clear photos of the damage.</p><form onSubmit={submit} style={{display:"grid",gap:14,marginTop:25}}><div className="grid" style={{gridTemplateColumns:"1fr 1fr"}}><input placeholder="Car make" value={make} onChange={e=>setMake(e.target.value)} required style={{padding:14,border:"1px solid #d8dee9",borderRadius:9}}/><input placeholder="Car model" value={model} onChange={e=>setModel(e.target.value)} required style={{padding:14,border:"1px solid #d8dee9",borderRadius:9}}/><input placeholder="Year" type="number" min="1950" max="2100" value={year} onChange={e=>setYear(e.target.value)} required style={{padding:14,border:"1px solid #d8dee9",borderRadius:9}}/><input placeholder="Registration number (optional)" value={registration} onChange={e=>setRegistration(e.target.value)} style={{padding:14,border:"1px solid #d8dee9",borderRadius:9}}/></div><input placeholder="City" value={city} onChange={e=>setCity(e.target.value)} required style={{padding:14,border:"1px solid #d8dee9",borderRadius:9}}/><div style={{padding:20,border:"2px dashed #cbd5e1",borderRadius:12}}><h3>Damage photos</h3><p className="muted">Upload up to 10 photos. Use clear photos from different angles.</p><input ref={input} type="file" accept="image/*" multiple onChange={e=>addPhotos(e.target.files)} style={{marginTop:10}}/><p className="muted">{photos.length} photo{photos.length===1?"":"s"} selected</p>{photos.length>0&&<ul>{photos.map((p,i)=><li key={`${p.name}-${i}`}>{p.name}</li>)}</ul>}</div><button className="btn primary" disabled={busy} type="submit">{busy?"Saving...":"Create assessment"}</button>{message&&<p className="muted">{message}</p>}</form></div></div></main>;
}
