export default function TermsPage() {
  return (
    <main className="legal-page"><article className="legal-card">
      <a className="legal-logo" href="/">Car<span>Fix</span></a>
      <p className="legal-kicker">LEGAL</p><h1>Terms of Service</h1><p className="legal-updated">Last updated: 25 September 2026</p>
      <p>These Terms govern use of CarFix, an AI-based car body repair assessment platform operated by Carflix. By creating an account, submitting an assessment or purchasing a paid assessment, you agree to these Terms.</p>
      <h2>CarFix assessments</h2><p>CarFix analyses customer-provided photographs, vehicle details, descriptions and, where applicable, location information to provide preliminary information about visible exterior body damage, dents, scratches, paint damage and possible body-panel repair or replacement.</p>
      <h2>AI-generated results</h2><p>Assessments are generated using artificial intelligence and depend on the material supplied by the customer. Results may contain inaccuracies or miss damage. A CarFix assessment is not a physical inspection, professional workshop quotation, engineering report, insurance assessment or guarantee of repair requirements or cost.</p>
      <h2>Repair-cost estimates</h2><p>Repair prices vary by location, workshop, vehicle, parts availability and repair method. Any CarFix cost range is guidance only and may be higher or lower than a workshop's final quotation. Customers should obtain a physical inspection and final quotation from a qualified repair professional before proceeding with repairs.</p>
      <h2>Customer responsibilities</h2><p>You are responsible for providing accurate information and clear photographs, having the right to upload submitted material, reviewing AI results before relying on them, keeping account credentials secure and using CarFix lawfully.</p>
      <h2>Free and paid assessments</h2><p>The first eligible customer assessment is currently free. Subsequent eligible assessments currently cost ₹199 per assessment. The applicable price is displayed before payment. Future pricing changes apply prospectively.</p>
      <h2>Payments, failures and refunds</h2><p>Payments are processed through the payment provider integrated with CarFix. Failed transactions and applicable payment-provider reversals follow the provider, bank, card network or payment instrument process. A failed payment does not unlock a paid assessment. If payment succeeds but a paid CarFix assessment cannot be delivered because of a CarFix service or processing failure, the issue may be reported through the support and grievance channel; where a refund is appropriate it will be processed through the applicable payment provider.</p>
      <h2>Assessment availability</h2><p>Assessment-related information is generally intended to remain available in the customer account for up to 20 days. Customers should review or save information they wish to retain before it is automatically deleted or becomes unavailable. CarFix does not promise permanent storage of assessment reports or uploaded material.</p>
      <h2>Uploads and permission to process</h2><p>By uploading photographs, documents, descriptions or other material, you confirm that you have the right to provide it and permit CarFix and the technology providers necessary to operate the service to process it for the requested assessment and for service security and operation.</p>
      <h2>Scope and limitations</h2><p>CarFix primarily assesses visible exterior body and paint-related damage. Unless expressly stated otherwise, it should not be treated as an assessment of mechanical, electrical, safety, structural, tyre, interior, glass, advanced driver-assistance or hidden vehicle conditions. Damage found during physical inspection or disassembly may differ from the AI assessment.</p>
      <h2>Workshops and repair decisions</h2><p>Workshop or repair information displayed by CarFix is informational. The customer remains responsible for choosing a repair provider, obtaining a final quotation and deciding whether to proceed. Agreements with independent workshops are separate from the CarFix AI assessment service unless expressly stated otherwise.</p>
      <h2>Availability and prohibited use</h2><p>CarFix may be temporarily unavailable because of maintenance, networks, third-party interruptions, security events or other technical circumstances. You must not attempt unauthorised access, upload harmful material, abuse payment or assessment functionality, submit fraudulent information or interfere with service security.</p>
      <h2>Liability and consumer rights</h2><p>CarFix provides preliminary guidance about visible damage and possible costs. To the extent permitted by law, CarFix is not responsible for differences caused by hidden damage, poor or incomplete photographs, local pricing, parts availability or information unavailable to the AI. Nothing in these Terms is intended to exclude rights or remedies that cannot lawfully be excluded.</p>
      <h2>Support, grievances and changes</h2><p>Questions, technical issues, payment-service concerns and grievances may be submitted through the CarFix support and grievance chatbot when available. These Terms may be updated as the service, business practices or applicable requirements change.</p>
      <nav className="legal-links"><a href="/privacy">Privacy Policy</a><a href="/ai-disclaimer">AI Disclaimer</a><a href="/">Back to CarFix</a></nav>
    </article></main>
  );
}
