"use client";
import { FormEvent, useState } from "react";
import { createClient } from "@/lib/supabase";
function normalizePhone(value: string) { const digits = value.replace(new RegExp("\\D","g"),""); return digits.startsWith("91") ? "+" + digits : "+91" + digits; }
export default function LoginPage() {
 const [phone,setPhone]=useState(""); const [otp,setOtp]=useState(""); const [otpSent,setOtpSent]=useState(false); const [message,setMessage]=useState(""); const supabase=createClient();
 async function sendOtp(e: FormEvent) { e.preventDefault(); setMessage("Sending OTP..."); const normalizedPhone=normalizePhone(phone); if(normalizedPhone.length!==13)return setMessage("Enter a valid 10-digit Indian mobile number."); const {error}=await supabase.auth.signInWithOtp({phone:normalizedPhone,options:{shouldCreateUser:false}}); if(error)return setMessage(error.message); setOtpSent(true); setMessage("OTP sent. Enter the code below."); }
 async function verifyOtp(e: FormEvent) { e.preventDefault(); setMessage("Verifying OTP..."); const normalizedPhone=normalizePhone(phone); const {error}=await supabase.auth.verifyOtp({phone:normalizedPhone,token:otp,type:"sms"}); if(error)return setMessage(error.message); window.location.href="/dashboard"; }
 return <main className="auth-page"><div className="auth-orb"/><a className="auth-logo" href="/">Car<span>Fix</span></a><div className="auth-card"><div className="auth-kicker">CUSTOMER ACCESS</div><h1>Welcome back.</h1><p className="muted">Sign in securely with your verified mobile number.</p>{!otpSent?<form onSubmit={sendOtp} className="auth-form"><label>Mobile number<input type="tel" placeholder="10-digit Indian mobile number" value={phone} onChange={e=>setPhone(e.target.value)} required inputMode="numeric" maxLength={10}/></label><div className="otp-note"><b>One-time verification</b><br/>We’ll send a secure OTP to your registered number.</div><button className="home-primary-btn auth-submit" type="submit">Send OTP</button>{message&&<p className="auth-message">{message}</p>}</form>:<form onSubmit={verifyOtp} className="auth-form"><label>Verification code<input className="otp-input" type="text" placeholder="••••••" value={otp} onChange={e=>setOtp(e.target.value.replace(new RegExp("\\D","g"),""))} required inputMode="numeric" maxLength={6} autoComplete="one-time-code"/></label><button className="home-primary-btn auth-submit" type="submit">Verify OTP &amp; Sign in</button><button className="auth-link-btn" type="button" onClick={()=>{setOtpSent(false);setMessage("")}}>Change phone number</button>{message&&<p className="auth-message">{message}</p>}</form>}<p className="auth-bottom">New to CarFix? <a href="/register">Create an account</a></p></div></main>;
}